[package]

name = "markdown"
version = "0.1.2"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "Native Rust library for parsing Markdown and (outputting HTML)"
repository = "https://github.com/johannhof/markdown.rs"
readme = "README.md"
keywords = ["markdown", "md", "html", "parser"]
license = "MIT"

exclude = [
    "test.md"
]

[[bin]]
name = "markdown"
doc = false

[features]
default = []
unstable = []

[dependencies]
regex = "0.1.41"
pipeline = "0.5.0"

[dev-dependencies]
difference = "0.4"

